name: Cronitor Monitoring Relay
on:
  workflow_run:
    workflows: ['BTS Ticket Monitor']
    types: [requested, completed]

jobs:
  send-telemetry:
    runs-on: ubuntu-latest
    steps:
      - name: Send telemetry to Cronitor
        uses: cronitorio/monitor-github-actions@v8
        with:
          event: ${{ toJSON(github.event) }}
          cronitor_key: ${{ secrets.CRONITOR_API_KEY }}
          github_token: ${{ secrets.G_TOKEN }}
